version: '3.8'
services:
  flask-app:
    image: ${DOCKER_IMAGE:-financial-microservice}:${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"  # برای scrape توسط Prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml  # فایل rules جدید
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'